### ISSUE TITLE
[BUG] build fails when MATX_EN_VISUALIZATION=ON

### ISSUE THREAD

**Issue by pkestene** [NVIDIA/MatX#273]
**Describe the bug**
Examples spectrogram and spectrogram_graph (and test also) fail to build when MATX_EN_VISUALIZATION is ON.
I guess this is due to some earlier refactoring. I manage to fix build by just including "matx/core/viz.h" in the examples and in `test/00_tensor/VizTests.cu`

**Additional context**
Now the build is OK, but the executable runs with a seg fault, apparently happening when loading plotly module (see below the stack trace).
I checked that plotly is correctly installed, so I don't exactly why it fails at runtime (both with release and debug MatX builds).

Here is the gdb trace on my system (Ubuntu 22.04, cuda-11.7, python 3.10 from ubuntu, no-conda):
```shell
Thread 1 "spectrogram" received signal SIGSEGV, Segmentation fault.
0x00007ffff7afcab1 in _PyUnicode_FromId () from /lib/x86_64-linux-gnu/libpython3.10.so.1.0
(cuda-gdb) bt
#0  0x00007ffff7afcab1 in _PyUnicode_FromId () from /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#1  0x00007ffff7b8b673 in PyImport_Import () from /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#2  0x00007ffff7b8b8fe in PyImport_ImportModule () from /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#3  0x0000555555573f51 in pybind11::module_::import (name=0x5555555a6b45 "plotly.graph_objects")
    at /data/pkestene/install/nvidia/MatX/git/MatX/build_debug/_deps/pybind11-src/include/pybind11/pybind11.h:992
#4  0x0000555555580014 in matx::viz::contour<matx::tensor_t<float, 1, matx::basic_storage<matx::raw_pointer_buffer<float, matx::matx_allocator<float> > >, matx::tensor_desc_t<std::array<long long, 1ul>, std::array<long long, 1ul>, 1> >, matx::tensor_t<float, 2, matx::basic_storage<matx::raw_pointer_buffer<cuda::std::__4::complex<float>, matx::matx_allocator<cuda::std::__4::complex<float> > > >, matx::tensor_desc_t<std::array<long long, 2ul>, std::array<long long, 2ul>, 2> > > (x=..., y=..., z=..., out_fname=...)
    at /data/pkestene/install/nvidia/MatX/git/MatX/include/matx/core/viz.h:276
#5  0x0000555555563460 in main (argc=1, argv=0x7fffffffdb28) at /data/pkestene/install/nvidia/MatX/git/MatX/examples/spectrogram.cu:140
```
Here is the check that the plotly module is installed in ipython:
```shell
 pkestene   main {1} U:3  /data/pkestene/install/nvidia/MatX/git/MatX/build_debug/examples  ipython3 
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.31.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import plotly.express as px

In [2]: 
```

Any advice on how to check that pybind11 is working correcly, I may have missed something.

**Comment by cliffburdick** [comment]
Hi @pkestene this should be fixed now. It was broken in some refactoring, but should be resolved. Thanks for the PR too. I'll take a look at it soon.

**Comment by pkestene** [comment]
indeed, working nice now. Thanks.
